/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author vagishadeo
 */

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.JOptionPane;
import model.Uber;
import model.UberCatalogue;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Scanner;
import java.util.concurrent.TimeUnit;
import javax.swing.JPanel;


public class CreatePanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePanel
     */
    
    UberCatalogue ubercatalogue;
    
    public CreatePanel(UberCatalogue ubercatalogue) {
        initComponents();
        this.ubercatalogue = ubercatalogue;
    }

    public CreatePanel() {
        initComponents();
     
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelDesign = new javax.swing.JLabel();
        buttonDesign = new javax.swing.JButton();

        labelDesign.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        labelDesign.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDesign.setText("Design Uber");

        buttonDesign.setText("Design Sample Uber Catalogue");
        buttonDesign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDesignActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(labelDesign, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(buttonDesign, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDesign, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonDesign, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1562, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDesignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDesignActionPerformed
        // TODO add your handling code here:

        File file = new File("/Users/vagishadeo/Desktop/Uberdoc.txt");

        Scanner scanner = null;
        try {
            scanner = new Scanner(file);
        } 
        catch (FileNotFoundException ex) {
            
        }
        while(scanner.hasNextLine()){
           
            
              String text = scanner.nextLine();
              String[] word = text.split(",");
             
              
              Uber newUber = ubercatalogue.addUber();
              newUber.setCar_create(word[0].trim());
              newUber.setManufacture_year(Integer.parseInt(word[1].trim()));
              newUber.setSeat_count(Integer.parseInt(word[2].trim()));
              newUber.setSerial_no(word[4].trim());
              newUber.setModel_no(Integer.parseInt(word[3].trim()));
              newUber.setPlace(word[5].trim());
              newUber.setMaintenance(Integer.parseInt(word[6].trim()));
              newUber.setAvailable_status(word[7].trim());
              newUber.setAvailable_date(word[8].trim());     
        
        }
        
        JOptionPane.showMessageDialog(this, "Design sample for uber saved");
        scanner.close();
        
 
    }//GEN-LAST:event_buttonDesignActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDesign;
    private javax.swing.JLabel labelDesign;
    // End of variables declaration//GEN-END:variables
}
