/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;


import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Uber;
import model.UberCatalogue;

/**
 *
 * @author vagishadeo
 */


public class ViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPanel
     */
    
   UberCatalogue ubercatalogue;
    
    public ViewPanel(UberCatalogue ubercatalogue) 
    {
        initComponents();
        
        this.ubercatalogue = ubercatalogue;
        
        populateTable();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelViewUber = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUberView = new javax.swing.JTable();
        ViewButton = new javax.swing.JButton();
        ButtonDelete = new javax.swing.JButton();
        car_create = new javax.swing.JLabel();
        car_create_text = new javax.swing.JTextField();
        manufacture_year = new javax.swing.JLabel();
        manufacture_year_text = new javax.swing.JTextField();
        seat_count = new javax.swing.JLabel();
        seat_count_text = new javax.swing.JTextField();
        serial_no = new javax.swing.JLabel();
        serial_no_text = new javax.swing.JTextField();
        model_no = new javax.swing.JLabel();
        model_no_text = new javax.swing.JTextField();
        place = new javax.swing.JLabel();
        place_text = new javax.swing.JTextField();
        maintenance = new javax.swing.JLabel();
        maintenance_text = new javax.swing.JTextField();
        available_status = new javax.swing.JLabel();
        available_status_text = new javax.swing.JTextField();

        labelViewUber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelViewUber.setText("View Uber Information");

        tableUberView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Uber Brand", "Seat Count", "Manufacture Year", "Model Number", "Serial Number", "City", "Maintenance ", "Availability Status", "Availability date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableUberView);

        ViewButton.setText("View");
        ViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewButtonActionPerformed(evt);
            }
        });

        ButtonDelete.setText("Delete");
        ButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteActionPerformed(evt);
            }
        });

        car_create.setText("Create");

        manufacture_year.setText("Year of Manufacture");

        manufacture_year_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manufacture_year_textActionPerformed(evt);
            }
        });

        seat_count.setText("Number of seats");

        seat_count_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat_count_textActionPerformed(evt);
            }
        });

        serial_no.setText("Serial Number");

        serial_no_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serial_no_textActionPerformed(evt);
            }
        });

        model_no.setText("Model Number");

        model_no_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                model_no_textActionPerformed(evt);
            }
        });

        place.setText("City ");

        place_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place_textActionPerformed(evt);
            }
        });

        maintenance.setText("Year of Maintenance");

        maintenance_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintenance_textActionPerformed(evt);
            }
        });

        available_status.setText("Availability Status");

        available_status_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                available_status_textActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(711, Short.MAX_VALUE)
                .addComponent(ViewButton)
                .addGap(28, 28, 28)
                .addComponent(ButtonDelete)
                .addGap(96, 96, 96))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 959, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelViewUber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(66, 66, 66))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(53, 53, 53)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(maintenance)
                        .addComponent(place)
                        .addComponent(model_no)
                        .addComponent(serial_no)
                        .addComponent(seat_count)
                        .addComponent(car_create)
                        .addComponent(available_status)
                        .addComponent(manufacture_year))
                    .addGap(128, 128, 128)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(manufacture_year_text, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(car_create_text)
                            .addComponent(seat_count_text)
                            .addComponent(serial_no_text)
                            .addComponent(model_no_text)
                            .addComponent(place_text)
                            .addComponent(maintenance_text)
                            .addComponent(available_status_text, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(369, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(labelViewUber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonDelete)
                    .addComponent(ViewButton))
                .addContainerGap(568, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(303, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(car_create)
                        .addComponent(car_create_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(21, 21, 21)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(manufacture_year)
                        .addComponent(manufacture_year_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(29, 29, 29)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(seat_count, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(seat_count_text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(28, 28, 28)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(serial_no)
                        .addComponent(serial_no_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(32, 32, 32)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(model_no)
                        .addComponent(model_no_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(24, 24, 24)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(place)
                        .addComponent(place_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(24, 24, 24)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(maintenance)
                        .addComponent(maintenance_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(29, 29, 29)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(available_status)
                        .addComponent(available_status_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(151, 151, 151)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewButtonActionPerformed
        // TODO add your handling code here:
        int SelectedRowIndex = tableUberView.getSelectedRow();
        if(SelectedRowIndex<0)
        {
            JOptionPane.showMessageDialog(this,"Please select data that has to be viewed");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tableUberView.getModel();
        Uber selectedUbers = (Uber) model.getValueAt(SelectedRowIndex, 0);

        car_create_text.setText(selectedUbers.getCar_create());
        manufacture_year_text.setText(String.valueOf(selectedUbers.getManufacture_year()));
        serial_no_text.setText(selectedUbers.getSerial_no());
        model_no_text.setText(String.valueOf(selectedUbers.getModel_no()));
        place_text.setText(selectedUbers.getPlace());
        maintenance_text.setText(String.valueOf(selectedUbers.getMaintenance()));
        available_status_text.setText(selectedUbers.getAvailable_status());

    }//GEN-LAST:event_ViewButtonActionPerformed

    private void ButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteActionPerformed
        // TODO add your handling code here:
        int SelectedRowIndex = tableUberView.getSelectedRow();
        if(SelectedRowIndex<0)
        {
            JOptionPane.showMessageDialog(this,"Please select data that has to be deleted");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tableUberView.getModel();
        Uber selectedUbers = (Uber) model.getValueAt(SelectedRowIndex, 0);

        Uber.deleteUber(selectedUbers);

        JOptionPane.showMessageDialog(this,"Selected Uber deleted");

        populateTable();

    }//GEN-LAST:event_ButtonDeleteActionPerformed

    private void manufacture_year_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manufacture_year_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manufacture_year_textActionPerformed

    private void seat_count_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat_count_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seat_count_textActionPerformed

    private void serial_no_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serial_no_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serial_no_textActionPerformed

    private void model_no_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_model_no_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_model_no_textActionPerformed

    private void place_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_place_textActionPerformed

    private void maintenance_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintenance_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maintenance_textActionPerformed

    private void available_status_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_available_status_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_available_status_textActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDelete;
    private javax.swing.JButton ViewButton;
    private javax.swing.JLabel available_status;
    private javax.swing.JTextField available_status_text;
    private javax.swing.JLabel car_create;
    private javax.swing.JTextField car_create_text;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelViewUber;
    private javax.swing.JLabel maintenance;
    private javax.swing.JTextField maintenance_text;
    private javax.swing.JLabel manufacture_year;
    private javax.swing.JTextField manufacture_year_text;
    private javax.swing.JLabel model_no;
    private javax.swing.JTextField model_no_text;
    private javax.swing.JLabel place;
    private javax.swing.JTextField place_text;
    private javax.swing.JLabel seat_count;
    private javax.swing.JTextField seat_count_text;
    private javax.swing.JLabel serial_no;
    private javax.swing.JTextField serial_no_text;
    private javax.swing.JTable tableUberView;
    // End of variables declaration//GEN-END:variables

    private void populateTable() 
    
    {
        
        DefaultTableModel design = (DefaultTableModel)tableUberView.getModel();
        design.setRowCount(0);
        
        
        for(Uber uber:ubercatalogue.getUber_catalogue()){
            Object[] data = new Object[9];
            System.out.println(uber.getCar_create());
            data[0] = uber.getCar_create();
            data[1] = uber.getManufacture_year();
            data[2] = uber.getSeat_count();
            data[3] = uber.getSerial_no();
            data[4] = uber.getModel_no();
            data[5] = uber.getPlace();
            data[6] = uber.getMaintenance();
            data[7] = uber.getAvailable_status();
            data[8] = uber.getAvailable_date();
            
            design.addRow(data);

        }
        
    }




}
